apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "porpulsion.fullname" . }}-credentials
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "porpulsion.fullname" . }}-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "porpulsion.fullname" . }}-credentials
  apiGroup: rbac.authorization.k8s.io
