apiVersion: v1
kind: Service
metadata:
  name: {{ include "porpulsion.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: agent
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "porpulsion.fullname" . }}-agent
  ports:
    - name: http
      port: {{ .Values.service.uiPort }}
      targetPort: {{ .Values.service.uiPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.uiNodePort }}
      nodePort: {{ .Values.service.uiNodePort }}
      {{- end }}
    - name: mtls
      port: {{ .Values.service.agentPort }}
      targetPort: {{ .Values.service.agentPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.agentNodePort }}
      nodePort: {{ .Values.service.agentNodePort }}
      {{- end }}
